### PR TITLE
Add linking to pcre if it is installed on the system

### PR DESCRIPTION
**Pull request by tdm4**
Detect PCRE library and if found, link to that instead of internal PCRE.

### CODE REVIEW

**Comment by namtsui** [comment]
```
Remove link to dl as it is in OpenBSD's libc
Have Cmake find and link to devel/pcre instead of the outdated bundled pcre
Index: CMakeLists.txt
--- CMakeLists.txt.orig
+++ CMakeLists.txt
@@ -59,8 +59,6 @@ set(SRC_COMMON
 	"${DIR_SRC}/vfs_pak.c"
 	"${DIR_SRC}/world.c"
 	"${DIR_SRC}/zone.c"
-	"${DIR_SRC}/pcre/get.c"
-	"${DIR_SRC}/pcre/pcre.c"
 	)
 
 # Check build target, and included sources
@@ -89,7 +87,25 @@ else()
 	)
 endif()
 
+######################################################################################################
 
+# Check for PCRE. if found, include it; if not found, use bundled PCRE.
+find_library(PCRE_LIBRARIES pcre)
+if(PCRE_LIBRARIES)
+	set(PCRE_FOUND 1)
+	find_path(PCRE_INCLUDE_DIR pcre.h)
+endif(PCRE_LIBRARIES)
+
+if(NOT PCRE_FOUND)
+	message(STATUS "PCRE library not found. Using bundled PCRE intead.")
+	list(APPEND SRC_COMMON
+	    "${DIR_SRC}/pcre/get.c"
+	    "${DIR_SRC}/pcre/pcre.c"
+	)
+else()
+	message(STATUS "Found PCRE: ${PCRE_LIBRARIES}")
+endif()
+
 ######################################################################################################
 
 # Set base compiler flags
@@ -111,6 +127,7 @@ set_target_properties(${PROJECT_NAME}
 
 # Set include directories
 target_include_directories(${PROJECT_NAME} PRIVATE ${CURL_INCLUDE_DIRS})
+target_include_directories(${PROJECT_NAME} PRIVATE ${PCRE_INCLUDE_DIR})
 
 
 ######################################################################################################
@@ -118,7 +135,6 @@ target_include_directories(${PROJECT_NAME} PRIVATE ${C
 # Check build target, and included sources and libs
 if(UNIX)
 	target_link_libraries(${PROJECT_NAME} m)
-	target_link_libraries(${PROJECT_NAME} dl)
 else()
 	target_link_libraries(${PROJECT_NAME} ws2_32)
 	target_link_libraries(${PROJECT_NAME} winmm)
@@ -147,6 +163,9 @@ if(CURL_FOUND)
 	target_link_libraries(${PROJECT_NAME} ${CURL_LIBRARIES})
 endif()
 
+if(PCRE_FOUND)
+	target_link_libraries(${PROJECT_NAME} ${PCRE_LIBRARIES})
+endif()
 
 ######################################################################################################
 ```

**Comment by namtsui** [comment]
I tweaked your patch a bit. (ignore the removal of dl.)
- use PCRE_FOUND and target_include_directories instead of include_directories to make it more like the existing CMakeLists curl bits
- no need for mark_as_advanced
- only compile bundled pcre (get.c and pcre.c) if system pcre isn't found. it is based on the logic here: https://github.com/QW-Group/mvdsv/pull/41

**Comment by tdm4** [comment]
@namtsui Yeah those look better. I've updated the branch to suit.

**Comment by tdm4** [comment]
I've also added some logic so that the 'dl' library is only linked if the OS is UNIX but not OpenBSD (which has -ldl in base)

**Comment by namtsui** [comment]
oops I had a typo: Using bundled PCRE intead --> instead

**Comment by namtsui** [comment]
I don't think the !OpenBSD works. It should be like this:
if(NOT CMAKE_SYSTEM_NAME MATCHES OpenBSD)

**Comment by tcsabina** [comment]
@tdm4 ,
The Github Actions are failing on the linux builds with this. Do you see the build logs above?

Toma

**Comment by namtsui** [comment]
> I don't think the !OpenBSD works. It should be like this: if(NOT CMAKE_SYSTEM_NAME MATCHES "OpenBSD")

Try running it again after tdm4 updates. It needs to be changed as mentioned above in order to link dl. As it currently is, !OpenBSD doesn't match Linux.

**Comment by tdm4** [comment]
@tcsabina @namtsui I've updated the branch to fix the If statement logic.

**Comment by namtsui** [comment]
> oops I had a typo: Using bundled PCRE intead --> instead

fix this typo, too

**Comment by tcsabina** [comment]
> @tcsabina @namtsui I've updated the branch to fix the If statement logic. Do I need to squash my commits, or are they OK as is?

Hi!
They are okay as is.
And I don't mind having a couple of commits, instead of only one, even for a PR...

**Comment by tcsabina** [comment]
@tdm4 ,
Have you seen the request/discussion about adding quotes around OpenBSD?

**Comment by tdm4** [comment]
> @tdm4 , Have you seen the request/discussion about adding quotes around OpenBSD?

Yes, my apologies! I've updated the branch and put double quotes around OpenBSD.
I think it should be good to go?

**Comment by tcsabina** [comment]
hi @tdm4 ,
I am sorry as well. Haven't seen somehow your reply on this, just now.
Let's check the pipeline, and if it is green, I think we are good to go!

**Pull request merged**
